// Code generated by github.com/gokultp/go-envparser. DO NOT EDIT.
package configs

import (
	"os"
	"strings"
)

func (t *GithubConfig) DecodeEnv() error {
	if _recClientidStr := os.Getenv("GITHUB_CLIENT_ID"); _recClientidStr != "" {
		_recClientid := _recClientidStr
		t.ClientID = &_recClientid
	}
	if _recClientsecretStr := os.Getenv("GITHUB_CLIENT_SECRET"); _recClientsecretStr != "" {
		_recClientsecret := _recClientsecretStr
		t.ClientSecret = &_recClientsecret
	}
	if _recAuthscopesStr := os.Getenv("GITHUB_AUTH_SCOPES"); _recAuthscopesStr != "" {
		_recAuthscopesArr := strings.Split(_recAuthscopesStr, ":")
		for _, _recAuthscopesStr := range _recAuthscopesArr {
			_recAuthscopes := _recAuthscopesStr
			t.AuthScopes = append(t.AuthScopes, _recAuthscopes)
		}
	}
	if _recAuthredirectStr := os.Getenv("GITHUB_AUTH_REDIRECT"); _recAuthredirectStr != "" {
		_recAuthredirect := _recAuthredirectStr
		t.AuthRedirect = &_recAuthredirect
	}
	return nil
}
