// Code generated by github.com/gokultp/go-envparser. DO NOT EDIT.
package configs

import (
	"os"
)

func (t *RedisConfig) DecodeEnv() error {
	if _recPortStr := os.Getenv("REDIS_PORT"); _recPortStr != "" {
		_recPort := _recPortStr
		t.Port = &_recPort
	}
	if _recHostStr := os.Getenv("REDIS_HOST"); _recHostStr != "" {
		_recHost := _recHostStr
		t.Host = &_recHost
	}
	if _recPasswordStr := os.Getenv("REDIS_PASSWORD"); _recPasswordStr != "" {
		_recPassword := _recPasswordStr
		t.Password = &_recPassword
	}
	return nil
}
