// Code generated by github.com/gokultp/go-envparser. DO NOT EDIT.
package configs

import (
	"os"
	"strconv"
)

func (t *UsersServiceConfig) DecodeEnv() error {
	if _recUrlStr := os.Getenv("USER_SERVICE_URL"); _recUrlStr != "" {
		_recUrl := _recUrlStr
		t.URL = &_recUrl
	}
	if _recInitconnectionsStr := os.Getenv("USER_SERVICE_INIT_CONN"); _recInitconnectionsStr != "" {
		_recInitconnections64, err := strconv.ParseInt(_recInitconnectionsStr, 10, 32)
		if err != nil {
			return err
		}
		_recInitconnections := int(_recInitconnections64)
		t.InitConnections = &_recInitconnections
	}
	if _recConnectioncapacityStr := os.Getenv("USER_SERVICE_CONN_CAPACITY"); _recConnectioncapacityStr != "" {
		_recConnectioncapacity64, err := strconv.ParseInt(_recConnectioncapacityStr, 10, 32)
		if err != nil {
			return err
		}
		_recConnectioncapacity := int(_recConnectioncapacity64)
		t.ConnectionCapacity = &_recConnectioncapacity
	}
	if _recTtlStr := os.Getenv("USER_SERVICE_CONN_TTL"); _recTtlStr != "" {
		_recTtl64, err := strconv.ParseInt(_recTtlStr, 10, 32)
		if err != nil {
			return err
		}
		_recTtl := int(_recTtl64)
		t.TTL = &_recTtl
	}
	return nil
}
