// Code generated by github.com/firstcontributions/matro. DO NOT EDIT.

package storiesstore

import "time"

type Reaction struct {
	StoryID     string    `bson:"story_id"`
	CreatedBy   string    `bson:"created_by,omitempty"`
	Id          string    `bson:"_id"`
	TimeCreated time.Time `bson:"time_created,omitempty"`
	TimeUpdated time.Time `bson:"time_updated,omitempty"`
}

func NewReaction() *Reaction {
	return &Reaction{}
}

type ReactionUpdate struct {
	TimeUpdated *time.Time `bson:"time_updated,omitempty"`
}

type ReactionFilters struct {
	Ids       []string
	CreatedBy *string
	Story     *Story
}
