// Code generated by github.com/firstcontributions/matro. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/firstcontributions/backend/internal/models/storiesstore"
	"github.com/firstcontributions/backend/internal/storemanager"
)

type StoryReactionsInput struct {
	First     *int32
	Last      *int32
	After     *string
	Before    *string
	SortBy    *string
	SortOrder *string
}

func (n *Story) Reactions(ctx context.Context, in *StoryReactionsInput) (*ReactionsConnection, error) {
	var first, last *int64
	if in.First != nil {
		tmp := int64(*in.First)
		first = &tmp
	}
	if in.Last != nil {
		tmp := int64(*in.Last)
		last = &tmp
	}
	store := storemanager.FromContext(ctx)

	filters := &storiesstore.ReactionFilters{
		Story: n.ref,
	}
	data, hasNextPage, hasPreviousPage, firstCursor, lastCursor, err := store.StoriesStore.GetReactions(
		ctx,
		filters,
		in.After,
		in.Before,
		first,
		last,
		in.SortBy,
		in.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	return NewReactionsConnection(filters, data, hasNextPage, hasPreviousPage, &firstCursor, &lastCursor), nil
}
