// Code generated by github.com/firstcontributions/matro. DO NOT EDIT.

package mongo

import (
	"context"
	"errors"
	"time"

	"github.com/firstcontributions/backend/internal/models/storiesstore"
	"github.com/firstcontributions/backend/internal/models/utils"
	"github.com/firstcontributions/backend/pkg/cursor"
	"github.com/gokultp/go-mongoqb"
	"github.com/google/uuid"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func commentFiltersToQuery(filters *storiesstore.CommentFilters) *mongoqb.QueryBuilder {
	qb := mongoqb.NewQueryBuilder()
	if len(filters.Ids) > 0 {
		qb.In("_id", filters.Ids)
	}
	if filters.CreatedBy != nil {
		qb.Eq("created_by", filters.CreatedBy)
	}
	if filters.Story != nil {
		qb.Eq("story_id", filters.Story.Id)
	}
	return qb
}
func (s *StoriesStore) CreateComment(ctx context.Context, comment *storiesstore.Comment) (*storiesstore.Comment, error) {
	now := time.Now()
	comment.TimeCreated = now
	comment.TimeUpdated = now
	uuid, err := uuid.NewUUID()
	if err != nil {
		return nil, err
	}
	comment.Id = uuid.String()
	if _, err := s.getCollection(CollectionComments).InsertOne(ctx, comment); err != nil {
		return nil, err
	}
	return comment, nil
}

func (s *StoriesStore) GetCommentByID(ctx context.Context, id string) (*storiesstore.Comment, error) {
	qb := mongoqb.NewQueryBuilder().
		Eq("_id", id)
	var comment storiesstore.Comment
	if err := s.getCollection(CollectionComments).FindOne(ctx, qb.Build()).Decode(&comment); err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return &comment, nil
}

func (s *StoriesStore) GetOneComment(ctx context.Context, filters *storiesstore.CommentFilters) (*storiesstore.Comment, error) {
	qb := commentFiltersToQuery(filters)
	var comment storiesstore.Comment
	if err := s.getCollection(CollectionComments).FindOne(ctx, qb.Build()).Decode(&comment); err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return &comment, nil
}

func (s *StoriesStore) CountComments(ctx context.Context, filters *storiesstore.CommentFilters) (
	int64,
	error,
) {
	qb := commentFiltersToQuery(filters)

	count, err := s.getCollection(CollectionComments).CountDocuments(ctx, qb.Build())
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (s *StoriesStore) GetComments(
	ctx context.Context,
	filters *storiesstore.CommentFilters,
	after *string,
	before *string,
	first *int64,
	last *int64,
	sortBy *string,
	sortOrder *string,
) (
	[]*storiesstore.Comment,
	bool,
	bool,
	string,
	string,
	error,
) {
	qb := commentFiltersToQuery(filters)

	limit, order, cursorStr := utils.GetLimitAndSortOrderAndCursor(first, last, after, before)
	var c *cursor.Cursor
	if cursorStr != nil {
		c = cursor.FromString(*cursorStr)
		if c != nil {
			if order == 1 {
				qb.Or(
					qb.And(
						qb.Eq(c.SortBy, c.OffsetValue),
						qb.Gt("_id", c.ID),
					),
					qb.Gt(c.SortBy, c.OffsetValue),
				)
			} else {
				qb.Or(
					qb.And(
						qb.Eq(c.SortBy, c.OffsetValue),
						qb.Lt("_id", c.ID),
					),
					qb.Lt(c.SortBy, c.OffsetValue),
				)
			}
		}
	}
	// incrementing limit by 2 to check if next, prev elements are present
	limit += 2
	options := &options.FindOptions{
		Limit: &limit,
		Sort:  utils.GetSortOrder(sortBy, sortOrder, order),
	}

	var firstCursor, lastCursor string
	var hasNextPage, hasPreviousPage bool

	var comments []*storiesstore.Comment
	mongoCursor, err := s.getCollection(CollectionComments).Find(ctx, qb.Build(), options)
	if err != nil {
		return nil, hasNextPage, hasPreviousPage, firstCursor, lastCursor, err
	}
	err = mongoCursor.All(ctx, &comments)
	if err != nil {
		return nil, hasNextPage, hasPreviousPage, firstCursor, lastCursor, err
	}
	count := len(comments)
	if count == 0 {
		return comments, hasNextPage, hasPreviousPage, firstCursor, lastCursor, nil
	}

	// check if the cursor element present, if yes that can be a prev elem
	if c != nil && comments[0].Id == c.ID {
		hasPreviousPage = true
		comments = comments[1:]
		count--
	}

	// check if actual limit +1 elements are there, if yes trim it to limit
	if count >= int(limit)-1 {
		hasNextPage = true
		comments = comments[:limit-2]
		count = len(comments)
	}

	if count > 0 {
		firstCursor = cursor.NewCursor(comments[0].Id, "time_created", comments[0].TimeCreated).String()
		lastCursor = cursor.NewCursor(comments[count-1].Id, "time_created", comments[count-1].TimeCreated).String()
	}
	if order < 0 {
		hasNextPage, hasPreviousPage = hasPreviousPage, hasNextPage
		firstCursor, lastCursor = lastCursor, firstCursor
		comments = utils.ReverseList(comments)
	}
	return comments, hasNextPage, hasPreviousPage, firstCursor, lastCursor, nil
}

func (s *StoriesStore) UpdateComment(ctx context.Context, id string, commentUpdate *storiesstore.CommentUpdate) error {
	qb := mongoqb.NewQueryBuilder().
		Eq("_id", id)

	now := time.Now()
	commentUpdate.TimeUpdated = &now

	u := mongoqb.NewUpdateMap().
		SetFields(commentUpdate)

	um, err := u.BuildUpdate()
	if err != nil {
		return err
	}
	if _, err := s.getCollection(CollectionComments).UpdateOne(ctx, qb.Build(), um); err != nil {
		return err
	}
	return nil
}

func (s *StoriesStore) DeleteCommentByID(ctx context.Context, id string) error {
	qb := mongoqb.NewQueryBuilder().
		Eq("_id", id)
	if _, err := s.getCollection(CollectionComments).DeleteOne(ctx, qb.Build()); err != nil {
		return err
	}
	return nil
}
