// Code generated by github.com/firstcontributions/matro. DO NOT EDIT.

package utils

import (
	"errors"

	"go.mongodb.org/mongo-driver/bson"
)

const (
	defaultLimit int64 = 10
	defaultOrder int   = 1
)

func GetLimitAndSortOrderAndCursor(first, last *int64, after, before *string) (int64, int, *string, error) {
	if first == nil && last == nil {
		return 0, 1, nil, errors.New("first or last is mandatory")
	}
	if (first != nil && before != nil) || (last != nil && after != nil) || (first != nil && last != nil) {
		return 0, 1, nil, errors.New("conflicting pagination parameters")
	}
	if first != nil {
		return *first, 1, after, nil
	}
	return *last, -1, before, nil
}

func GetSortOrder(sortBy string, order int) bson.D {
	return bson.D{
		{sortBy, order},
		{"_id", order},
	}
}

func GetSortOrderFromString(order *string) int {
	if order != nil && *order == "asc" {
		return 1
	}
	return -1
}

func ReverseList[T interface{}](list []*T) []*T {
	ln := len(list)
	for i := 0; i < ln/2; i++ {
		list[i], list[ln-1-i] = list[ln-1-i], list[i]
	}
	return list
}
